services:
  asisya-db:
    image: postgres:16-alpine
    container_name: asisya_postgres_db
    restart: always
    environment:
      POSTGRES_DB: asisya_db
      POSTGRES_USER: asisya_user
      POSTGRES_PASSWORD: asisya_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init/01_init_schema.sql:/docker-entrypoint-initdb.d/01_init_schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U asisya_user -d asisya_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  asisya-redis:
    image: redis:7-alpine
    container_name: asisya_redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  asisya-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: asisya_backend_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Host=asisya-db;Port=5432;Database=asisya_db;Username=asisya_user;Password=asisya_password
      - ConnectionStrings__Redis=asisya-redis:6379
      - JwtSettings__Secret=AsisyaPruebaTecnicaSuperSecretKey2026Net8JwtValidation!
      - JwtSettings__Issuer=AsisyaApi
      - JwtSettings__Audience=AsisyaClients
      - JwtSettings__ExpiryMinutes=120
    depends_on:
      asisya-db:
        condition: service_healthy
      asisya-redis:
        condition: service_healthy

  asisya-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: asisya_frontend_spa
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - asisya-backend

volumes:
  postgres_data:
  redis_data:
